### ISSUE TITLE
Real variables can't be assigned the result of abs function

### ISSUE THREAD

**Issue by danilociaffi** [r-koubou/KSPSyntaxParser#11]
I am using a real variable and I am experiencing the following error at save:

`[KSP] ":=" : not compatible type (Real := Void)`

I tried stripping down the code as much as I could to find my mistake and indeed I get this error even in toy examples as this:

```
on init
  declare ~real_test
  ~real_test := abs(1.0)
end on
```

Love this extension btw, I hope this can be fixed soon :)

**Comment by r-koubou** [comment]
Done.
Please update vscode extension 👍

**Comment by danilociaffi** [comment]
Thanks, that works! Unfortunately now I get `[KSP] := not compatible type (Integer := Void)` with the `real_to_int()` and `int_to_real()` functions (I swear it's not on purpose to bring int to real back and forth, I needed it in my script).

```
on init
	declare $real_test
	$real_test := real_to_int(1.0)
end on
```

**Comment by r-koubou** [comment]
Thank you, I think it's the same cause as the abs function, so please wait.
I will check the other functions and update vscode extension again in a few days.

**Comment by r-koubou** [comment]
If you want to work around the `int_to_real` and `real_to_int` bugs right away, you can do so in the following steps.

#### 1: Download commands.txt

[commands.txt](https://github.com/r-koubou/KSPSyntaxParser/files/5638490/commands.txt)

#### 2: Copy commands.txt to the following location

**Windows**
> C:\Users\\\<UserName\>\\.vscode\extensions\rkoubou.ksp-0.7.14\kspparser\data\symbols

**macOS**
> ~/.vscode/extensions/rkoubou.ksp-0.7.14/kspparser/data/symbols

#### 3: restart vscode

**Comment by danilociaffi** [comment]
Thank you!

**Comment by r-koubou** [comment]
Uploaded vscode extension. Please update  to latest version 0.7.15.

- [CHANGELOG](https://github.com/r-koubou/vscode-ksp/blob/master/CHANGELOG.md)

**Comment by danilociaffi** [comment]
Awesome, thank you!
